feat: add select uninitialized participants on internal criteria #11
empiricaly/recruitment pull request #28
Opened 2020-11-24 07:45 UTC by hubertusputu1

## Context 
#11 

## Features
- [x] able to select uninitialized participants from imported participants on internal DB

2020-11-24 09:00 UTC, npaton requested changes
Good stuff 👍 
Couple of changes. And also one missing change in the answer.go file, that's another place we will add Participants, and I actually wonder if it might be the only place we add new Participants eventually, so we should probably have the same logic you have for `endMTurkHITStep()` in there too. Please let me know if my memory is wrong and something is not happening like I think it is. 👍

2020-11-24 09:00 UTC, npaton commented on internal/mturk/step.go
> +			if *p.Uninitialized != false {
You're dereferencing a pointer without checking if it's null first: `p.Uninitialized != null && *p.Uninitialized != false`.

2020-11-24 09:00 UTC, npaton commented on internal/mturk/step.go
> +					log.Error().Msgf("could not set participant unitialized with workerID %s for stepRun ", *assignment.WorkerId, stepRun.ID)
uninitialized

2020-11-24 09:00 UTC, npaton commented on internal/runtime/process.go
> +		initializedParticipants = participants
This should actually be the opposite of below (could be one loop I think), we only want uninitialized participants if true. The idea is we want to select only uninitialized participants to make them go through a HIT so they are now initialized, so we want to be able to isolate them in both directions (only initialized / only uninitialized).

2020-11-24 09:00 UTC, npaton commented on web/src/components/templates/Template.svelte
> +            question="Uninitialized Participants are Participants that have been imported, and do not yet have a HIT associated with them, so we cannot send messages or bonuses to them" />
I guess given my previous comment, we should add some details here. At the end of the description, you can add: 

"Uninitialized participants are *not* included in an Internal DB selection. On the contrary, if you check this box, *only* uninitialized participants will be selected."

Hum, that's a bit of a mouthful... Hopefully at least it's clear.

2020-11-24 11:29 UTC, hubertusputu1 commented
Yes, you are correct, we create another participant on `answers.go` file, i have already added it on there as well.

2020-11-24 11:38 UTC, npaton requested changes
I don't think the participant filter is capturing the logic yet, see inline comment.

2020-11-24 11:38 UTC, npaton commented on internal/runtime/process.go
> +	}
`if !unitilized` (don't need to compare a boolean) you don't know filter out uninitialized?

I think all that's needed is to have a condition that handles both opposite cases in the loop below:

```go
if (!uninitialized && participant.Uninitialized != nil && *participant.Uninitialized) || (uninitialized && (participant.Uninitialized == nil || !*participant.Uninitialized))
```

2020-11-25 02:14 UTC, npaton approved these changes

2020-11-25 02:15 UTC, merged